{% set name = "alembic" %}
{% set version = "0.9.6" %}
{% set hash_type = "sha256" %}
{% set hash = "042851ebe9efa07be6dc1395b1793b6c1d8964a39b73a0ce1649e2bcd41ea732" %}
{% set bundle = "tar.gz" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  entry_points:
    - alembic = alembic.config:main
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - sqlalchemy >=0.7.6
    - mako
    - python-editor >=0.3
    - python-dateutil

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util

  commands:
    - alembic --help

about:
  home: https://bitbucket.org/zzzeek/alembic
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'A database migration tool for SQLAlchemy.'
  dev_url: https://bitbucket.org/zzzeek/alembic
  doc_url: http://alembic.zzzcomputing.com/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
