{% set name = "alembic" %}
{% set version = "1.15.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alembic-{{ version }}.tar.gz
  sha256: 1c72391bbdeffccfe317eefba686cb9a3c078005478885413b95c3b26c57a8a7

build:
  noarch: python
  entry_points:
    - alembic = alembic.config:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.2
  run:
    - python >={{ python_min }}
    - sqlalchemy >=1.4.0
    - mako
    - typing_extensions >=4.12

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util
  commands:
    - pip check
    - alembic --help

about:
  home: https://alembic.sqlalchemy.org/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A database migration tool for SQLAlchemy.
  dev_url: https://github.com/sqlalchemy/alembic
  doc_url: http://alembic.zzzcomputing.com/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - xylar
