{% set name = "alembic" %}
{% set version = "1.14.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alembic-{{ version }}.tar.gz
  sha256: b00892b53b3642d0b8dbedba234dbf1924b69be83a9a769d5a624b01094e304b

build:
  noarch: python
  entry_points:
    - alembic = alembic.config:main
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
  run:
    - python >={{ python_min }}
    - sqlalchemy >=1.3.0
    - mako
    # Keeping noarch: python
    - importlib-metadata
    - importlib_resources
    - typing_extensions >=4

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util
  commands:
    - pip check
    - alembic --help

about:
  home: https://alembic.sqlalchemy.org/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A database migration tool for SQLAlchemy.
  dev_url: https://github.com/sqlalchemy/alembic
  doc_url: http://alembic.zzzcomputing.com/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - xylar
