schema_version: 1

context:
  name: alembic
  version: 1.20.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/alembic-${{ version }}.tar.gz
  sha256: db505480647bc60386c5369402f4a57a506b7539c9e9ef5e270d45cbbe4939bf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  python:
    entry_points:
      - alembic = alembic.config:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=77.0.3
  run:
    - python >=${{ python_min }}
    - sqlalchemy >=2.0
    - mako
    - typing_extensions >=4.12
tests:
  - python:
      imports:
        - alembic
        - alembic.autogenerate
        - alembic.ddl
        - alembic.operations
        - alembic.runtime
        - alembic.script
        - alembic.util
      python_version:
        - ${{ python_min }}.*
        - '*'
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - alembic --help

about:
  license_file: LICENSE
  license: MIT
  summary: A database migration tool for SQLAlchemy.
  homepage: https://alembic.sqlalchemy.org/
  repository: https://github.com/sqlalchemy/alembic
  documentation: http://alembic.zzzcomputing.com/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - xylar
