schema_version: 1

context:
  name: alembic
  version: 1.17.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/alembic-${{ version }}.tar.gz
  sha256: bbe9751705c5e0f14877f02d46c53d10885e377e3d90eda810a016f9baa19e8e

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  python:
    entry_points:
      - alembic = alembic.config:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=77.0.3
  run:
    - python >=${{ python_min }}
    - sqlalchemy >=1.4.0
    - mako
    - typing_extensions >=4.12
    # for python <3.11 but adding it for all since we're noarch: python
    - tomli

tests:
  - python:
      imports:
        - alembic
        - alembic.autogenerate
        - alembic.ddl
        - alembic.operations
        - alembic.runtime
        - alembic.script
        - alembic.util
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - alembic --help

about:
  license_file: LICENSE
  license: MIT
  summary: A database migration tool for SQLAlchemy.
  homepage: https://alembic.sqlalchemy.org/
  repository: https://github.com/sqlalchemy/alembic
  documentation: http://alembic.zzzcomputing.com/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - xylar
